Study_Maps={'20251016UTa':{'collection':'20251016-20251016',
                            '3':{'plotoptions':[],
                                 #'CoLatLims':[45,135],
                                 #'LonRng':45,
                                 #'CMpref':255},
                                 'CoLatLims':[0,180],
                                 'LonRng':60,
                                 'CMpref':260},
                            '1':{'plotoptions':["scatter","resid","correl"],
                                 'CoLatLims':[75,105],
                                 #'LonRng':45,
                                 #'CMpref':280,
                                 'LonRng':60,
                                 'CMpref':290,
                                 'NEZ-East':{'ROI':{"Hot Spot":[82,84,267.0,2.0],
                                                   "Gyre":[85,87,270.0,3.0],
                                                   "Cloud Plume":[82,84,262.0,2.0],
                                                   "Reference":[75,77,270.0,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':270
                                            },
                                 'NEZ-West':{'ROI':{"Hot Spot":[81,82,297.0,2.0],
                                                   "Gyre":[83,86,299.0,4.0],
                                                   "Cloud Plume":[81,83,293.0,2.0],
                                                   "Reference":[75,77,295.0,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':295
                                            }
                                 }

                            },
            '20251016UTb':{'collection':'20251016-20251016',
                            '3':{'plotoptions':[],
                                 #'CoLatLims':[45,135],
                                 #'LonRng':45,
                                 #'CMpref':255},
                                 'CoLatLims':[0,180],
                                 'LonRng':60,
                                 'CMpref':270},
                            '1':{'plotoptions':["scatter","resid","correl"],
                                 'CoLatLims':[75,105],
                                 #'LonRng':45,
                                 #'CMpref':280,
                                 'LonRng':60,
                                 'CMpref':300,
                                 'NEZ-East':{'ROI':{"Hot Spot":[82,84,267.0,2.0],
                                                   "Gyre":[85,87,270.0,3.0],
                                                   "Cloud Plume":[82,84,262.0,2.0],
                                                   "Reference":[75,77,270.0,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':270
                                            },
                                 'NEZ-West':{'ROI':{"Hot Spot":[81,82,297.0,2.0],
                                                   "Gyre":[83,86,299.0,4.0],
                                                   "Cloud Plume":[81,83,293.0,2.0],
                                                   "Reference":[75,77,295.0,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':295
                                            }
                                 }

                            },
            '20251016UTc':{'collection':'20251017-20251017',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':30,
                                'CMpref':30},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                'LonRng':45,
                                'CMpref':45,
                                #'CoLatLims':[75,90],
                                #'LonRng':15,
                                #'CMpref':15,
                                'NEZ-East':{'ROI':{"Hot Spot":[82,83,14.0,2.0],
                                                  "Gyre":[84,86,15.0,3.0],
                                                  "Cloud Plume":[82,84,5.0,3.0],
                                                  "Reference":[76,78,15,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':15
                                           },
                                'NEZ-West':{'ROI':{"Hot Spot":[83,84,53.0,2.0],
                                                  "Gyre":[84,85,53.0,3.0],
                                                  "Cloud Plume":[84,86,34.0,3.0],
                                                  "Reference":[76,78,45,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':45
                                           },
                                'SEZ-SED':{'ROI':{"Hot Spot":[98,100,61.0,2.0],
                                                  "Gyre":[95,97,63.0,4.0],
                                                  "Cloud Plume":[96,98,53.0,2.0],
                                                  "Reference":[104,105,60,8.0]},
                                           'CoLatLims':[90,105],
                                           'LonRng':15,
                                           'CMpref':60
                                           },
                                'SEZ-SED-Ext':{'ROI':{"Hot Spot":[98,100,61.0,2.0],
                                                  "Gyre":[95,97,63.0,4.0],
                                                  "Cloud Plume":[96,98,53.0,2.0],
                                                  "Reference":[102,103,55,8.0]},
                                           'CoLatLims':[85,105],
                                           'LonRng':30,
                                           'CMpref':50
                                           }
                                }

                           },
            '20251016UTd':{'collection':'20251017-20251017',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':45},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                'LonRng':60,
                                'CMpref':60,
                                #'CoLatLims':[75,90],
                                #'LonRng':15,
                                #'CMpref':15,
                                'NEZ-East':{'ROI':{"Hot Spot":[82,83,14.0,2.0],
                                                  "Gyre":[84,86,15.0,3.0],
                                                  "Cloud Plume":[82,84,5.0,3.0],
                                                  "Reference":[76,78,15,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':15
                                           },
                                'NEZ-West':{'ROI':{"Hot Spot":[83,84,53.0,2.0],
                                                  "Gyre":[84,85,53.0,3.0],
                                                  "Cloud Plume":[84,86,34.0,3.0],
                                                  "Reference":[76,78,45,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':45
                                           },
                                'SEZ-SED':{'ROI':{"Hot Spot":[98,100,61.0,2.0],
                                                  "Gyre":[95,97,63.0,4.0],
                                                  "Cloud Plume":[96,98,53.0,2.0],
                                                  "Reference":[104,105,60,8.0]},
                                           'CoLatLims':[90,105],
                                           'LonRng':15,
                                           'CMpref':60
                                           }
                                }

                           },
            '20251016UTe':{'collection':'20251017-20251017',
                           '3':{'plotoptions':["contours"],
                                #'CoLatLims':[45,135],
                                #'LonRng':45,
                                #'CMpref':90},
                                'CoLatLims':[0,180],
                                'LonRng':60,
                                'CMpref':70},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':45,
                                #'CMpref':105,
                                'LonRng':60,
                                'CMpref':95,
                                'NEZ-East':{'ROI':{"Hot Spot":[83,85,96.0,3.0],
                                                  "Gyre":[85,87,98.0,4.0],
                                                  "Cloud Plume":[82,84,79.0,3.0],
                                                  "Reference":[76,78,90.0,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':90
                                           },
                                'NEZ-West':{'ROI':{"Hot Spot":[82,84,125.0,3.0],
                                                  "Gyre":[84,86,126.0,3.0],
                                                  "Cloud Plume":[82,84,113.0,3.0],
                                                  "Reference":[76,78,120.0,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':120
                                           },
                                'SEZ-SED':{'ROI':{"Hot Spot":[98,100,61.0,2.0],
                                                  "Gyre":[95,97,63.0,4.0],
                                                  "Cloud Plume":[96,98,53.0,2.0],
                                                  "Reference":[104,105,60,8.0]},
                                           'CoLatLims':[90,105],
                                           'LonRng':15,
                                           'CMpref':60
                                           }
                                }

                           },
            '20251016UTf':{'collection':'20251017-20251017',
                           '3':{'plotoptions':["contours"],
                                #'CoLatLims':[45,135],
                                #'LonRng':45,
                                #'CMpref':90},
                                'CoLatLims':[0,180],
                                'LonRng':60,
                                'CMpref':80},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':45,
                                #'CMpref':105,
                                'LonRng':60,
                                'CMpref':105,
                                'NEZ-East':{'ROI':{"Hot Spot":[83,85,96.0,3.0],
                                                  "Gyre":[85,87,98.0,4.0],
                                                  "Cloud Plume":[82,84,79.0,3.0],
                                                  "Reference":[76,78,90.0,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':90
                                           },
                                'NEZ-West':{'ROI':{"Hot Spot":[82,84,125.0,3.0],
                                                  "Gyre":[84,86,126.0,3.0],
                                                  "Cloud Plume":[82,84,113.0,3.0],
                                                  "Reference":[76,78,120.0,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':120
                                           },
                                'SEZ-SED':{'ROI':{"Hot Spot":[98,100,61.0,2.0],
                                                  "Gyre":[95,97,63.0,4.0],
                                                  "Cloud Plume":[96,98,53.0,2.0],
                                                  "Reference":[104,105,60,8.0]},
                                           'CoLatLims':[90,105],
                                           'LonRng':15,
                                           'CMpref':60
                                           }
                                }

                           },
            '20251120UTa':{'collection':'20251116-20251116',
                           '3':{'plotoptions':["contours"],
                                #'CoLatLims':[45,135],
                                #'LonRng':30,
                                #'CMpref':135},
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':120},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':65
                                'LonRng':45,
                                'CMpref':60,
                                'NEZ':{'ROI':{"Hot Spot":[81,82,64,2.0],
                                                  "Gyre":[83,85,64,4.0],
                                                  "Cloud Plume":[84,86,55,3.0],
                                                  "Reference":[76,78,60,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':60
                                           }

                                }

                           },
            '20251120UTb':{'collection':'20251119-20251119',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':290},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':230,
                                'LonRng':45,
                                'CMpref':230,
                                'NEZ':{'ROI':{"Hot Spot":[81,82,215.0,3.0],
                                                  "Gyre":[83,85,215.0,4.0],
                                                  "Cloud Plume":[82,84,203.0,3.0],
                                                  "Reference":[76,78,215.0,4.0]},
                                           'CoLatLims':[75,90],
                                           'LonRng':15,
                                           'CMpref':215
                                           }

                                }

                           },
            '20251120UTc':{'collection':'20251119-20251119',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':50},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':330
                                'LonRng':30,
                                'CMpref':330,
                                 'NEZ':{'ROI':{"Hot Spot":[82,83,350,2.0],
                                                   "Gyre":[83,86,340,4.0],
                                                   "Cloud Plume":[82,83,332,3.0],
                                                   "Reference":[75,77,340,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':340
                                            }
                                 }

                           },
            '20251221UTa':{'collection':'20251222-20251222',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':90},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':250
                                'LonRng':60,
                                'CMpref':250,
                                'NEZ-East':{'ROI':{"Hot Spot":[82,83,225,2.0],
                                                   "Gyre":[83,85,221,3.0],
                                                   "Cloud Plume":[81,82,207,2.0],
                                                   "Reference":[75,77,220,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':220
                                            },
                                'NEZ-West':{'ROI':{"Hot Spot":[82,83,290,2.0],
                                                   "Gyre":[85,87,275,3.0],
                                                   "Cloud Plume":[81,82,270,2.0],
                                                   "Reference":[75,77,280,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':280
                                            },
                                'NEZ-West1':{'ROI':{"Hot Spot":[83,84,275,2.0],
                                                   "Gyre":[86,87,276,3.0],
                                                   "Cloud Plume":[82,83,271,2.0],
                                                   "Reference":[75,77,280,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':280
                                            }
                                }

                           },
            '20251221UTb':{'collection':'20251222-20251222',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':115},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':285
                                'LonRng':60,
                                'CMpref':280,
                                'NEZ-East':{'ROI':{"Hot Spot":[83,84,275,2.0],
                                                   "Gyre":[86,87,276,3.0],
                                                   "Cloud Plume":[82,83,271,2.0],
                                                   "Reference":[75,77,280,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':280
                                            },
                                'NEZ-West':{'ROI':{"Hot Spot":[82,83,305,2.0],
                                                   "Gyre":[84,85,307,3.0],
                                                   "Cloud Plume":[84,85,296,2.0],
                                                   "Reference":[75,77,305,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':305
                                            }
                                }

                           },
            '20251221UTc':{'collection':'20251222-20251222',
                           '3':{'plotoptions':["contours"],
                                'CoLatLims':[0,180],
                                'LonRng':45,
                                'CMpref':310},
                           '1':{'plotoptions':["scatter","resid","correl"],
                                'CoLatLims':[75,105],
                                #'LonRng':30,
                                #'CMpref':125
                                'LonRng':60,
                                'CMpref':125,
                                'NEZ-East':{'ROI':{"Hot Spot":[81,82,104,3.0],
                                                   "Gyre":[85,86,104,3.0],
                                                   "Cloud Plume":[81,82,95,2.0],
                                                   "Reference":[75,77,105,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':105
                                            },
                                'NEZ-West':{'ROI':{"Hot Spot":[81,82,139,2.0],
                                                   #"Hot Spot":[78,79,139,1.0], #Special deep convection
                                                   "Gyre":[84,85,139,3.0],
                                                   "Cloud Plume":[81,82,133,2.0],
                                                   "Reference":[75,77,140,5.0]},
                                            'CoLatLims':[75,90],
                                            'LonRng':15,
                                            'CMpref':140
                                            },
                                }

                           }

             }
